# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Music',
        ),
    ]
