# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0004_rate_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
