# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.TextField(default='song1'),
        ),
    ]
