# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.TextField()),
                ('type', models.TextField()),
                ('info', models.TextField()),
                ('temperature', models.TextField()),
                ('img', models.TextField()),
                ('date', models.TextField()),
                ('lastModifyDate', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
